# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'datrasview_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class DATRASViewDialog(QtWidgets.QDialog):
    def setupUi(self, DATRASViewDialog):
        DATRASViewDialog.setObjectName("DATRASViewDialog")
        DATRASViewDialog.resize(400, 764)
        self.verticalLayout = QtWidgets.QVBoxLayout(DATRASViewDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.get_datras_btn = QtWidgets.QPushButton(DATRASViewDialog)
        self.get_datras_btn.setObjectName("get_datras_btn")
        self.verticalLayout.addWidget(self.get_datras_btn)
        self.label_5 = QtWidgets.QLabel(DATRASViewDialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.year_combo = QtWidgets.QComboBox(DATRASViewDialog)
        self.year_combo.setObjectName("year_combo")
        self.verticalLayout.addWidget(self.year_combo)
        self.label = QtWidgets.QLabel(DATRASViewDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.quarter_combo = QtWidgets.QComboBox(DATRASViewDialog)
        self.quarter_combo.setObjectName("quarter_combo")
        self.verticalLayout.addWidget(self.quarter_combo)
        self.label_2 = QtWidgets.QLabel(DATRASViewDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.species_combo = QtWidgets.QComboBox(DATRASViewDialog)
        self.species_combo.setObjectName("species_combo")
        self.verticalLayout.addWidget(self.species_combo)
        self.label_11 = QtWidgets.QLabel(DATRASViewDialog)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.data_mode_tabs = QtWidgets.QTabWidget(DATRASViewDialog)
        self.data_mode_tabs.setMinimumSize(QtCore.QSize(0, 150))
        self.data_mode_tabs.setObjectName("data_mode_tabs")
        self.quantile_tab = QtWidgets.QWidget()
        self.quantile_tab.setObjectName("quantile_tab")
        self.layoutWidget = QtWidgets.QWidget(self.quantile_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 311, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(20, 0))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 1, 1, 1)
        self.data_mode_tabs.addTab(self.quantile_tab, "")
        self.threshold_tab = QtWidgets.QWidget()
        self.threshold_tab.setObjectName("threshold_tab")
        self.layoutWidget1 = QtWidgets.QWidget(self.threshold_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 11, 311, 102))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.min_lclass = QtWidgets.QSlider(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_lclass.sizePolicy().hasHeightForWidth())
        self.min_lclass.setSizePolicy(sizePolicy)
        self.min_lclass.setOrientation(QtCore.Qt.Horizontal)
        self.min_lclass.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.min_lclass.setTickInterval(5)
        self.min_lclass.setObjectName("min_lclass")
        self.gridLayout_2.addWidget(self.min_lclass, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(20, 0))
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.max_lclass = QtWidgets.QSlider(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_lclass.sizePolicy().hasHeightForWidth())
        self.max_lclass.setSizePolicy(sizePolicy)
        self.max_lclass.setOrientation(QtCore.Qt.Horizontal)
        self.max_lclass.setInvertedAppearance(True)
        self.max_lclass.setInvertedControls(False)
        self.max_lclass.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.max_lclass.setTickInterval(5)
        self.max_lclass.setObjectName("max_lclass")
        self.gridLayout_2.addWidget(self.max_lclass, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(20, 0))
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 1, 1, 1)
        self.data_mode_tabs.addTab(self.threshold_tab, "")
        self.verticalLayout.addWidget(self.data_mode_tabs)
        self.add_data_box = QtWidgets.QGroupBox(DATRASViewDialog)
        self.add_data_box.setMinimumSize(QtCore.QSize(0, 100))
        self.add_data_box.setObjectName("add_data_box")
        self.msize_check = QtWidgets.QCheckBox(self.add_data_box)
        self.msize_check.setGeometry(QtCore.QRect(20, 20, 88, 22))
        self.msize_check.setObjectName("msize_check")
        self.totnum_check = QtWidgets.QCheckBox(self.add_data_box)
        self.totnum_check.setGeometry(QtCore.QRect(20, 50, 171, 22))
        self.totnum_check.setObjectName("totnum_check")
        self.verticalLayout.addWidget(self.add_data_box)
        self.label_6 = QtWidgets.QLabel(DATRASViewDialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.layer_prefix_text = QtWidgets.QLineEdit(DATRASViewDialog)
        self.layer_prefix_text.setObjectName("layer_prefix_text")
        self.verticalLayout.addWidget(self.layer_prefix_text)
        self.sape_save_check = QtWidgets.QCheckBox(DATRASViewDialog)
        self.sape_save_check.setObjectName("sape_save_check")
        self.verticalLayout.addWidget(self.sape_save_check)
        self.pushButton = QtWidgets.QPushButton(DATRASViewDialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.button_box = QtWidgets.QDialogButtonBox(DATRASViewDialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(DATRASViewDialog)
        self.data_mode_tabs.setCurrentIndex(0)
        self.button_box.accepted.connect(DATRASViewDialog.accept)
        self.button_box.rejected.connect(DATRASViewDialog.reject)
        self.min_lclass.valueChanged['int'].connect(self.label_9.setNum)
        self.max_lclass.valueChanged['int'].connect(self.label_10.setNum)
        self.horizontalSlider.sliderMoved['int'].connect(self.label_8.setNum)
        QtCore.QMetaObject.connectSlotsByName(DATRASViewDialog)

    def retranslateUi(self, DATRASViewDialog):
        _translate = QtCore.QCoreApplication.translate
        DATRASViewDialog.setWindowTitle(_translate("DATRASViewDialog", "DATRAS Viewer"))
        self.get_datras_btn.setText(_translate("DATRASViewDialog", "1. Get DATRAS metadata"))
        self.label_5.setText(_translate("DATRASViewDialog", "2. Select year"))
        self.label.setText(_translate("DATRASViewDialog", "3. Select quarter"))
        self.label_2.setText(_translate("DATRASViewDialog", "4. Select species"))
        self.label_11.setText(_translate("DATRASViewDialog", "5. Select data selection method"))
        self.label_7.setText(_translate("DATRASViewDialog", "Select quantile"))
        self.label_8.setText(_translate("DATRASViewDialog", "0"))
        self.data_mode_tabs.setTabText(self.data_mode_tabs.indexOf(self.quantile_tab), _translate("DATRASViewDialog", "Quantile"))
        self.label_4.setText(_translate("DATRASViewDialog", "Min LC"))
        self.label_9.setText(_translate("DATRASViewDialog", "0"))
        self.label_3.setText(_translate("DATRASViewDialog", "Max LC"))
        self.label_10.setText(_translate("DATRASViewDialog", "0"))
        self.data_mode_tabs.setTabText(self.data_mode_tabs.indexOf(self.threshold_tab), _translate("DATRASViewDialog", "LC threshold"))
        self.add_data_box.setTitle(_translate("DATRASViewDialog", "6. Select additional layer data"))
        self.msize_check.setText(_translate("DATRASViewDialog", "Mean size"))
        self.totnum_check.setText(_translate("DATRASViewDialog", "Total number in haul"))
        self.label_6.setText(_translate("DATRASViewDialog", "7. Set output layer prefix"))
        self.sape_save_check.setText(_translate("DATRASViewDialog", "Save layer as shapefile"))
        self.pushButton.setText(_translate("DATRASViewDialog", "8. Create DATRAS layer"))

